<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RimWorks.Pickle.Vanilla</AssemblyName>
    <RootNamespace>RimWorks.Pickle.Vanilla</RootNamespace>
    <OutDir>$(MSBuildProjectDirectory)\..\..\Assemblies\</OutDir>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(GamecrateRefs)/*.dll" Condition="'$(HasGameRefs)' == 'true'"
               Exclude="$(GamecrateRefs)/System.*.dll;$(GamecrateRefs)/System.dll;$(GamecrateRefs)/Microsoft.*.dll;$(GamecrateRefs)/mscorlib.dll;$(GamecrateRefs)/netstandard.dll;$(GamecrateRefs)/WindowsBase.dll">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup Condition="'$(HasGameRefs)' == 'false'">
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*" ExcludeAssets="runtime" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.*" ExcludeAssets="runtime" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Pickle\Pickle.csproj" />
  </ItemGroup>
</Project>
